name: cppcheck

on:
  push:
    branches:
      - master

jobs:
  upload-sarif:
    runs-on: ubuntu-24.04
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - run: |
          sudo apt-get install -y cppcheck

      - run: |
          cppcheck --enable=all -I. --xml --suppress=missingIncludeSystem --std=c++20 --output-file=three_way_algorithms.xml .

      - uses: Flast/cppcheck-sarif@master
        with:
          input: three_way_algorithms.xml
          output: three_way_algorithms.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: three_way_algorithms.sarif
          category: cppcheck
